### ISSUE TITLE
turning on dvd zone 1 also turns on zone 2 (AVR-X2100)

### ISSUE THREAD

**Issue by kitopopo** [dnpwwo/Domoticz-Denon-Plugin#5]
hi dear friends,

I will try to explain in English the failure that I have found a fault in my Denon AVR-x2100.

When I turn on "Denon-Power" the "main zone" or "zone 2", boths zones are turned on at the same time.

If all have all zones off, and for instance I only select DVD in the "main zone", the "zone 2" on my amplifier also turns on, zone 2 . all zones are turned on. The same thing happens in reverse. 
Is impossible to turn on only the main zone and also is impossible to turn on only zone 2. The two zones are turning on at the same time.

ON the main zone input is not possible switch to tuner input , only i can select  DVD and CD inputs

On zone 2 i only can swtich to DVD input. 

Is it a widespread problem or does it only occur with my Denon AVR-x2100? Could you correct the problem? I would be eternally grateful. Thanks in advance and a warm greeting. Best regards

**Comment by kitopopo** [comment]
Dear @dnpwwo  and @bramvreugd  ,  I wish you are well.

I opened an issue about 10 months ago but have not received a response. This plugin is very important to me, I use it for everything in domoticz. Could you solve the problems? thanks in advance.  I would be very grateful to you. a cordial greeting

**Comment by bramvreugd** [comment]
Hi kitopopo,

Because I'm not the original author and I don't have zone 2 devices I'm not 100% sure what the problem is. I think I fixed it but it is also possible that the receiver won't turn on at all with zone 2 devices.

Attached is the file plugin_test_zones.txt. 
You should copy the file to your domoticz\plugins\Domoticz-Denon-Plugin directory. Rename your old plugin.py to something like plugin_original.py and rename the file plugin_test_zones.txt to plugin.py.
Restart domoticz and i hope it will work.
If it does not work copy the plugin_original.py back.
Please let me know if it works.

kind regards,
Bram Vreugdenhil
[plugin_test_zones.txt](https://github.com/dnpwwo/Domoticz-Denon-Plugin/files/4812101/plugin_test_zones.txt)

**Comment by kitopopo** [comment]
Dear friend, 

Sorry by the delay. I test your new plugin but and i have give to the new file execution permissions but i can read the following message in the domoticz log file: Error: Denon AV hardware (18) thread seems to have ended unexpectedly, 
Now no works the plugin. The denon devices appears dissabled. Can you recheck the new plugin?

Thanks in advanced. Best regards
